config/routes.rb
Rails.application.routes.draw do
  resources :leasing_cars
  resources :payment_cards
  resources :card_types
  resources :car_models
  resources :leasings
  resources :platforms
  resources :brand_types
  resources :cards
  resources :documents
  resources :addresses
  resources :payment_methods
  resources :rentaltypes
  resources :document_types
  resources :address_types
  resources :type_documents
  resources :type_addresses
  resources :people
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords",
    mailer: "users/mailer",
    confirmations: "users/confirmations",
    unlocks: "users/unlocks"
  }

 root "home#index"
end

app/models/user.rb
class User < ApplicationRecord
  has_one :people, dependent: :destroy
  accepts_nested_attributes_for :people

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook google_oauth2 github]

  def self.from_omniauth(auth)
    existing_user = User.find_by(email: auth.info.email)

    if existing_user
      existing_user.update!(provider: auth.provider, uid: auth.uid)
      existing_user
    else
      self.where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0, 20]
        user.password_confirmation = user.password
      end
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in(@user, bypass: true)
      @user.create_people unless @user.people

      if @user.people.additional_fields_required?
        session["devise.user_id"] = @user.id
        redirect_to edit_user_registration_url, notice: "Complete seu cadastro com informações adicionais."
      else
        sign_in_and_redirect @user, event: :authentication
        set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      end
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra)
      redirect_to new_user_registration_url
    end
  end

  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in(@user, bypass: true)
      @user.create_people unless @user.people

      if @user.people.additional_fields_required?
        session["devise.user_id"] = @user.id
        redirect_to edit_user_registration_url, notice: "Complete seu cadastro com informações adicionais."
      else
        sign_in_and_redirect @user, event: :authentication
        set_flash_message(:notice, :success, kind: "GitHub") if is_navigational_format?
      end
    else
      session["devise.github_data"] = request.env["omniauth.auth"].except(:extra)
      redirect_to new_user_registration_url
    end
  end

  def google_oauth2
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in(@user, bypass: true)
      @user.create_people unless @user.people

      if @user.people.additional_fields_required?
        session["devise.user_id"] = @user.id
        redirect_to edit_user_registration_url, notice: "Complete seu cadastro com informações adicionais."
      else
        sign_in_and_redirect @user, event: :authentication
        set_flash_message(:notice, :success, kind: "Google") if is_navigational_format?
      end
    else
      session['devise.google_data'] = request.env['omniauth.auth'].except(:extra)
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path, alert: "Falha na autenticação. Por favor, tente novamente."
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    # Constrói um novo recurso (usuário) usando os parâmetros fornecidos
    build_resource(sign_up_params)

    # Salva o recurso no banco de dados
    resource.save

    # Executa um bloco (se fornecido) passando o recurso como argumento
    yield resource if block_given?

    # Verifica se o recurso foi persistido no banco de dados com sucesso
    if resource.persisted?
      # Verifica se o usuário está ativo para autenticação
      if resource.active_for_authentication?
        # Configura a mensagem flash para o caso de registro bem-sucedido
        set_flash_message! :notice, :signed_up

        # Realiza o login do usuário
        sign_up(resource_name, resource)

        # Responde com o recurso, redirecionando para a página após o registro bem-sucedido
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        # Configura a mensagem flash para o caso de registro bem-sucedido, mas o usuário está inativo
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"

        # Expira os dados após o login e responde com o recurso, redirecionando para a página após o login
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      # Limpa os dados de senha e responde com o recurso, indicando que houve um problema no registro
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end
  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  private

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute,
                                      people_attributes: [:name, :last_name, :telephone, :birth_date, :adddress, :cpf]])
  end

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, people_attributes: [:name, :last_name, :telephone, :birth_date, :cpf, :address])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute, people_attributes: [:name, :last_name, :telephone, :birth_date, :address, :cpf]])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    super do |resource|
      Rails.logger.info("Usuário #{resource.email}. Deu bom Dai.")
    end
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Esqueceu sua senha?", new_password_path(resource_name), class: "text-decoration-none forgot-text" %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <div class="btn-group">
    <%- resource_class.omniauth_providers.each do |provider| %>
      <% if provider == :facebook %>
        <%= button_to omniauth_authorize_path(resource_name, provider), data: { turbo: false }, class: "btn btn-primary", style: "margin-right: 10px;" do %>
          <i class="bi bi-facebook"></i>
        <% end %>
      <% elsif provider == :google_oauth2 %>
        <%= button_to omniauth_authorize_path(resource_name, provider), data: { turbo: false }, class: "btn btn-danger ", style: "margin-right: 10px;" do %>
          <i class="bi bi-google"></i>
        <% end %>
      <% elsif provider == :github %>
        <%= button_to omniauth_authorize_path(resource_name, provider), data: { turbo: false }, method: :post, class: "btn btn-dark", style: "margin-right: 10px;" do %>
          <i class="bi bi-github"></i>
        <% end %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/users/shared/_people_attributes_fields.html.erb
<%= f.fields_for :people_attributes do |people_fields| %>
  <div class="form-data">
    <%= people_fields.label :name, "Nome" %><br />
    <%= people_fields.text_field :name, placeholder: "Nome", class: "form-control w-100" %>
  </div>
  <div class="form-data">
    <%= people_fields.label :last_name, "Sobrenome" %><br />
    <%= people_fields.text_field :last_name, placeholder: "Sobrenome", class: "form-control w-100" %>
  </div>
  <div class="form-data">
    <%= people_fields.label :telephone, "Telefone" %><br />
    <%= people_fields.text_field :telephone, placeholder: "Telefone", class: "form-control w-100" %>
  </div>
  <div class="form-data">
    <%= people_fields.label :birth_date, "Data de nascimento" %><br />
    <%= people_fields.date_field :birth_date, placeholder: "Data de nascimento" %>
  </div>
  <div class="form-data">
    <%= people_fields.label :cpf, "CPF/Cnpj" %><br />
    <%= people_fields.text_field :cpf, id: "cpf_cnpj_field", placeholder: "CPF/Cnpj:" %>
  </div>
  <div class="form-data">
    <%= people_fields.label :address, "Endereço" %><br />
    <%= people_fields.text_field :address, placeholder: "Endereço:", class: "form-control w-100" %>
  </div>
<% end %>