config/routes.rb
Rails.application.routes.draw do
  resources :leasing_cars
  resources :payment_cards
  resources :card_types
  resources :car_models
  resources :leasings
  resources :platforms
  resources :brand_types
  resources :cards
  resources :documents
  resources :addresses
  resources :payment_methods
  resources :rentaltypes
  resources :document_types
  resources :address_types
  resources :type_documents
  resources :type_addresses
  resources :people
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords",
    mailer: "users/mailer",
    confirmations: "users/confirmations",
    unlocks: "users/unlocks"
  }

 root "home#index"
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :people
  belongs_to :address_type
end

app/models/address_type.rb
class AddressType < ApplicationRecord
end

app/models/brand_type.rb
class BrandType < ApplicationRecord
end

app/models/car_model.rb
class CarModel < ApplicationRecord
  belongs_to :brand_type
  belongs_to :platform
end

app/models/card.rb
class Card < ApplicationRecord
end

app/models/card_type.rb
class CardType < ApplicationRecord
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :people
  belongs_to :document_type
end

app/models/document_type.rb
class DocumentType < ApplicationRecord
end

app/models/leasing.rb
class Leasing < ApplicationRecord
  belongs_to :leasing_type
  belongs_to :payment_method
  belongs_to :card
end

app/models/leasing_car.rb
class LeasingCar < ApplicationRecord
  belongs_to :leasing_type
  belongs_to :payment_method
  belongs_to :card
  belongs_to :car_model
  belongs_to :people
end

app/models/payment_card.rb
class PaymentCard < ApplicationRecord
end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
end

app/models/people.rb
class People < ApplicationRecord
  belongs_to :user, optional: true

  validates :address, presence: true, if: :additional_fields_required?
  validates :birth_date, presence: true, if: :additional_fields_required?
  validates :telephone, presence: true, if: :additional_fields_required?
  validates :cpf, uniqueness: true, presence: true, if: :additional_fields_required?
  validates :name, presence: true, if: :additional_fields_required?
  validates :last_name, presence: true, if: :additional_fields_required?

  def additional_fields_required?
    self.user.nil?
  end
end

app/models/platform.rb
class Platform < ApplicationRecord
end

app/models/rentaltype.rb
class Rentaltype < ApplicationRecord
end

app/models/type_address.rb
class TypeAddress < ApplicationRecord
end

app/models/type_document.rb
class TypeDocument < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_one :people, dependent: :destroy
  accepts_nested_attributes_for :people

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook google_oauth2 github]

  def self.from_omniauth(auth)
    existing_user = User.find_by(email: auth.info.email)

    if existing_user
      existing_user.update!(provider: auth.provider, uid: auth.uid)
      existing_user
    else
      self.where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0, 20]
        user.password_confirmation = user.password
      end
    end
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: %i[ show edit update destroy ]

  # GET /documents or /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1 or /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents or /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to document_url(@document), notice: "Document was successfully created." }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1 or /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to document_url(@document), notice: "Document was successfully updated." }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1 or /documents/1.json
  def destroy
    @document.destroy

    respond_to do |format|
      format.html { redirect_to documents_url, notice: "Document was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def document_params
      params.require(:document).permit(:people_id, :document_type_id, :number_document, :expiration_date)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/leasings_helper.rb
module LeasingsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/documents/_document.html.erb
<div id="<%= dom_id document %>">
  <p>
    <strong>People:</strong>
    <%= document.people_id %>
  </p>

  <p>
    <strong>Document type:</strong>
    <%= document.document_type_id %>
  </p>

  <p>
    <strong>Number document:</strong>
    <%= document.number_document %>
  </p>

  <p>
    <strong>Expiration date:</strong>
    <%= document.expiration_date %>
  </p>

</div>

app/views/documents/_form.html.erb
<%= form_with(model: document) do |form| %>
  <% if document.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
        <% document.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :people_id, style: "display: block" %>
    <%= form.text_field :people_id %>
  </div>

  <div>
    <%= form.label :document_type_id, style: "display: block" %>
    <%= form.text_field :document_type_id %>
  </div>

  <div>
    <%= form.label :number_document, style: "display: block" %>
    <%= form.text_field :number_document %>
  </div>

  <div>
    <%= form.label :expiration_date, style: "display: block" %>
    <%= form.date_field :expiration_date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing document</h1>

<%= render "form", document: @document %>

<br>

<div>
  <%= link_to "Show this document", @document %> |
  <%= link_to "Back to documents", documents_path %>
</div>

app/views/documents/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Documents</h1>

<div id="documents">
  <% @documents.each do |document| %>
    <%= render document %>
    <p>
      <%= link_to "Show this document", document %>
    </p>
  <% end %>
</div>

<%= link_to "New document", new_document_path %>

app/views/documents/new.html.erb
<h1>New document</h1>

<%= render "form", document: @document %>

<br>

<div>
  <%= link_to "Back to documents", documents_path %>
</div>

app/views/documents/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @document %>

<div>
  <%= link_to "Edit this document", edit_document_path(@document) %> |
  <%= link_to "Back to documents", documents_path %>

  <%= button_to "Destroy this document", @document, method: :delete %>
</div>