config/routes.rb
Rails.application.routes.draw do
  resources :leasing_cars
  resources :payment_cards
  resources :card_types
  resources :car_models
  resources :leasings
  resources :platforms
  resources :brand_types
  resources :cards
  resources :documents
  resources :addresses
  resources :payment_methods
  resources :rentaltypes
  resources :document_types
  resources :address_types
  resources :type_documents
  resources :type_addresses
  resources :people
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords",
    mailer: "users/mailer",
    confirmations: "users/confirmations",
    unlocks: "users/unlocks"
  }

 root "home#index"
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :people
  belongs_to :address_type
end

app/models/address_type.rb
class AddressType < ApplicationRecord
end

app/models/brand_type.rb
class BrandType < ApplicationRecord
end

app/models/car_model.rb
class CarModel < ApplicationRecord
  belongs_to :brand_type
  belongs_to :platform
end

app/models/card.rb
class Card < ApplicationRecord
end

app/models/card_type.rb
class CardType < ApplicationRecord
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :people
  belongs_to :document_type
end

app/models/document_type.rb
class DocumentType < ApplicationRecord
end

app/models/leasing.rb
class Leasing < ApplicationRecord
  belongs_to :leasing_type
  belongs_to :payment_method
  belongs_to :card
end

app/models/leasing_car.rb
class LeasingCar < ApplicationRecord
  belongs_to :leasing_type
  belongs_to :payment_method
  belongs_to :card
  belongs_to :car_model
  belongs_to :people
end

app/models/payment_card.rb
class PaymentCard < ApplicationRecord
end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
end

app/models/people.rb
class People < ApplicationRecord
  belongs_to :user, optional: true

  validates :address, presence: true, if: :additional_fields_required?
  validates :birth_date, presence: true, if: :additional_fields_required?
  validates :telephone, presence: true, if: :additional_fields_required?
  validates :cpf, uniqueness: true, presence: true, if: :additional_fields_required?
  validates :name, presence: true, if: :additional_fields_required?
  validates :last_name, presence: true, if: :additional_fields_required?

  def additional_fields_required?
    self.user.nil?
  end
end

app/models/platform.rb
class Platform < ApplicationRecord
end

app/models/rentaltype.rb
class Rentaltype < ApplicationRecord
end

app/models/type_address.rb
class TypeAddress < ApplicationRecord
end

app/models/type_document.rb
class TypeDocument < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_one :people, dependent: :destroy
  accepts_nested_attributes_for :people

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook google_oauth2 github]

  def self.from_omniauth(auth)
    existing_user = User.find_by(email: auth.info.email)

    if existing_user
      existing_user.update!(provider: auth.provider, uid: auth.uid)
      existing_user
    else
      self.where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0, 20]
        user.password_confirmation = user.password
      end
    end
  end
end

app/controllers/rentaltypes_controller.rb
class RentaltypesController < ApplicationController
  before_action :set_rentaltype, only: %i[ show edit update destroy ]

  # GET /rentaltypes or /rentaltypes.json
  def index
    @rentaltypes = Rentaltype.all
  end

  # GET /rentaltypes/1 or /rentaltypes/1.json
  def show
  end

  # GET /rentaltypes/new
  def new
    @rentaltype = Rentaltype.new
  end

  # GET /rentaltypes/1/edit
  def edit
  end

  # POST /rentaltypes or /rentaltypes.json
  def create
    @rentaltype = Rentaltype.new(rentaltype_params)

    respond_to do |format|
      if @rentaltype.save
        format.html { redirect_to rentaltype_url(@rentaltype), notice: "Rentaltype was successfully created." }
        format.json { render :show, status: :created, location: @rentaltype }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rentaltype.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rentaltypes/1 or /rentaltypes/1.json
  def update
    respond_to do |format|
      if @rentaltype.update(rentaltype_params)
        format.html { redirect_to rentaltype_url(@rentaltype), notice: "Rentaltype was successfully updated." }
        format.json { render :show, status: :ok, location: @rentaltype }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rentaltype.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rentaltypes/1 or /rentaltypes/1.json
  def destroy
    @rentaltype.destroy

    respond_to do |format|
      format.html { redirect_to rentaltypes_url, notice: "Rentaltype was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rentaltype
      @rentaltype = Rentaltype.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rentaltype_params
      params.require(:rentaltype).permit(:rental_type)
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/rentaltypes_helper.rb
module RentaltypesHelper
end

app/views/rentaltypes/_form.html.erb
<%= form_with(model: rentaltype) do |form| %>
  <% if rentaltype.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(rentaltype.errors.count, "error") %> prohibited this rentaltype from being saved:</h2>

      <ul>
        <% rentaltype.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :rental_type, style: "display: block" %>
    <%= form.text_field :rental_type %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/rentaltypes/_rentaltype.html.erb
<div id="<%= dom_id rentaltype %>">
  <p>
    <strong>Rental type:</strong>
    <%= rentaltype.rental_type %>
  </p>

</div>

app/views/rentaltypes/edit.html.erb
<h1>Editing rentaltype</h1>

<%= render "form", rentaltype: @rentaltype %>

<br>

<div>
  <%= link_to "Show this rentaltype", @rentaltype %> |
  <%= link_to "Back to rentaltypes", rentaltypes_path %>
</div>

app/views/rentaltypes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Rentaltypes</h1>

<div id="rentaltypes">
  <% @rentaltypes.each do |rentaltype| %>
    <%= render rentaltype %>
    <p>
      <%= link_to "Show this rentaltype", rentaltype %>
    </p>
  <% end %>
</div>

<%= link_to "New rentaltype", new_rentaltype_path %>

app/views/rentaltypes/new.html.erb
<h1>New rentaltype</h1>

<%= render "form", rentaltype: @rentaltype %>

<br>

<div>
  <%= link_to "Back to rentaltypes", rentaltypes_path %>
</div>

app/views/rentaltypes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @rentaltype %>

<div>
  <%= link_to "Edit this rentaltype", edit_rentaltype_path(@rentaltype) %> |
  <%= link_to "Back to rentaltypes", rentaltypes_path %>

  <%= button_to "Destroy this rentaltype", @rentaltype, method: :delete %>
</div>